[libraries]

[[library]]
name = "Imperium"
url = "https://github.com/giosuel/imperium/releases/download/v1.0.0/imperium_v1.0.0.zip"

[[library]]
name = "CodeRebirth"
url = "https://thunderstore.io/package/download/XuXiaolan/CodeRebirth/1.4.1/"

[[library]]
name="Malfunctions"
url= "https://thunderstore.io/package/download/zealsprince/Malfunctions/1.10.1/"